CREATE SCHEMA PAYROLL;
CREATE TABLE PAYROLL.DEPT (DEPT_ID INT, DEPT_CODE VARCHAR(10), DESCRIPTION VARCHAR(20), UNIT VARCHAR(5), CATEGORY VARCHAR(5));
CREATE TABLE PAYROLL.RATE (RATE_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, PERMANENT DOUBLE, SPECIAL_BADLY DOUBLE, BADLY DOUBLE, LEARNER DOUBLE, SEMI_SKILLED DOUBLE, NEW_ENTRANCE DOUBLE,
       OUTSIDER DOUBLE, OTHER_MILL DOUBLE, VOUCHER DOUBLE, STATUS VARCHAR(6), CREATED_BY VARCHAR(20), CREATED_DATE TIMESTAMP, UPDATED_BY VARCHAR(20), UPDATE_DATE TIMESTAMP,
       UNIQUE (RATE_ID, CURR_DATE),
       PRIMARY KEY(CURR_DATE));
       
CREATE TABLE PAYROLL.DEPT (DEPT_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			 DEPT_CODE VARCHAR(10) NOT NULL, DESCRIPTION VARCHAR(20), UNIT VARCHAR(1), CATEGORY VARCHAR(2),
       UNIQUE (DEPT_ID, DEPT_CODE),
       PRIMARY KEY(DEPT_CODE));


CREATE TABLE PAYROLL.PRODUCTION(PROD_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, PROD_VAL DOUBLE NOT NULL,
			UNIQUE (PROD_ID, CURR_DATE),
       		PRIMARY KEY(CURR_DATE));
       
CREATE TABLE PAYROLL.SINGLE_HANDS(SHAND_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, DEPT_CODE VARCHAR(10) NOT NULL, HAND_VALUE DOUBLE,
			UNIQUE (CURR_DATE,DEPT_CODE),
       		PRIMARY KEY(SHAND_ID),
       		FOREIGN KEY (DEPT_CODE) REFERENCES PAYROLL.DEPT(DEPT_CODE)); 
       		
       		
CREATE TABLE PAYROLL.DAILY_HANDS(DHAND_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, DEPT_CODE VARCHAR(10) NOT NULL,
			ENTRY_TYPE VARCHAR(1),
			PERMANENTA DOUBLE,
			PERMANENTB DOUBLE,
			PERMANENTC DOUBLE,
			SPECIALBADLYA DOUBLE,
			SPECIALBADLYB DOUBLE,
			SPECIALBADLYC DOUBLE,
			BADLYA DOUBLE,
			BADLYB DOUBLE,
			BADLYC DOUBLE,
			LEARNERA DOUBLE,
			LEARNERB DOUBLE,
			LEARNERC DOUBLE,
			SEMISKILLEDA DOUBLE,
			SEMISKILLEDB DOUBLE,
			SEMISKILLEDC DOUBLE,
			NEWENTRANCEA DOUBLE,
			NEWENTRANCEB DOUBLE,
			NEWENTRANCEC DOUBLE,
			OUTSIDERA DOUBLE,
			OUTSIDERB DOUBLE,
			OUTSIDERC DOUBLE,
			OTHERMILLA DOUBLE,
			OTHERMILLB DOUBLE,
			OTHERMILLC DOUBLE,
			VOUCHERRETA DOUBLE,
			VOUCHERRETB DOUBLE,
			VOUCHERRETC DOUBLE,
			UNIQUE (CURR_DATE,DEPT_CODE,ENTRY_TYPE),
			PRIMARY KEY(DHAND_ID),
			FOREIGN KEY (DEPT_CODE) REFERENCES PAYROLL.DEPT(DEPT_CODE));
       		
SELECT * FROM PAYROLL.DAILY_HANDS
       		
       		
       		
       		
       		
       		
       		
       		
       		
       		
       		
       		
       		
       
DROP TABLE PAYROLL.DAILY_HANDS 

       
  SELECT * FROM PAYROLL.DEPT
 
 DROP TABLE PAYROLL.RATE
 
 DELETE  FROM PAYROLL.DEPT WHERE DEPT_ID IN (32)
 
 