CREATE SCHEMA PAYROLL;
CREATE TABLE PAYROLL.RATE (RATE_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, PERMANENT DOUBLE, SPECIAL_BADLY DOUBLE, BADLY DOUBLE, LEARNER DOUBLE, SEMI_SKILLED DOUBLE, NEW_ENTRANCE DOUBLE,
       OUTSIDER DOUBLE, OTHER_MILL DOUBLE, VOUCHER DOUBLE, STATUS VARCHAR(6), CREATED_BY VARCHAR(20), CREATED_DATE TIMESTAMP, UPDATED_BY VARCHAR(20), UPDATE_DATE TIMESTAMP,
       UNIQUE (CURR_DATE),
       PRIMARY KEY(RATE_ID));
       
CREATE TABLE PAYROLL.DEPT (DEPT_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			 DEPT_CODE VARCHAR(10) NOT NULL, DESCRIPTION VARCHAR(20), UNIT VARCHAR(1), CATEGORY VARCHAR(2),
       UNIQUE (DEPT_CODE),
       PRIMARY KEY(DEPT_ID));

CREATE TABLE PAYROLL.PRODUCTION(
			CURR_DATE DATE NOT NULL, PROD_VAL DOUBLE NOT NULL, RATE_ID INTEGER NOT NULL,
			FOREIGN KEY (RATE_ID) REFERENCES PAYROLL.RATE(RATE_ID),
       		PRIMARY KEY(CURR_DATE));
       
CREATE TABLE PAYROLL.SINGLE_HANDS(SHAND_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, DEPT_ID INTEGER NOT NULL, HAND_VALUE DOUBLE,
			UNIQUE (CURR_DATE,DEPT_ID),
       		PRIMARY KEY(SHAND_ID),
       		FOREIGN KEY (DEPT_ID) REFERENCES PAYROLL.DEPT(DEPT_ID)); 
       		
       		
CREATE TABLE PAYROLL.DAILY_HANDS(DHAND_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
			CURR_DATE DATE NOT NULL, DEPT_ID INTEGER NOT NULL,
			ENTRY_TYPE VARCHAR(1),
			PERMANENTA DOUBLE,
			PERMANENTB DOUBLE,
			PERMANENTC DOUBLE,
			SPECIALBADLYA DOUBLE,
			SPECIALBADLYB DOUBLE,
			SPECIALBADLYC DOUBLE,
			BADLYA DOUBLE,
			BADLYB DOUBLE,
			BADLYC DOUBLE,
			LEARNERA DOUBLE,
			LEARNERB DOUBLE,
			LEARNERC DOUBLE,
			SEMISKILLEDA DOUBLE,
			SEMISKILLEDB DOUBLE,
			SEMISKILLEDC DOUBLE,
			NEWENTRANCEA DOUBLE,
			NEWENTRANCEB DOUBLE,
			NEWENTRANCEC DOUBLE,
			OUTSIDERA DOUBLE,
			OUTSIDERB DOUBLE,
			OUTSIDERC DOUBLE,
			OTHERMILLA DOUBLE,
			OTHERMILLB DOUBLE,
			OTHERMILLC DOUBLE,
			VOUCHERRETA DOUBLE,
			VOUCHERRETB DOUBLE,
			VOUCHERRETC DOUBLE,
			UNIQUE (CURR_DATE,DEPT_ID,ENTRY_TYPE),
			PRIMARY KEY(DHAND_ID),
			FOREIGN KEY (DEPT_ID) REFERENCES PAYROLL.DEPT(DEPT_ID));
       		
alter table PAYROLL.DAILY_HANDS add column TOTAL DOUBLE
SELECT * FROM PAYROLL.DAILY_HANDS
       		
drop table payroll.PRODUCTION;
drop table payroll.DAILY_HANDS;
drop table payroll.RATE
drop table payroll.DEPT
drop table payroll.SINGLE_HANDS
       		
       		


select * from payroll.RATE
select * from PAYROLL.PRODUCTION
insert into PAYROLL.PRODUCTION(curr_date, PROD_VAL,rate_id) values ( '2018-02-23', 49.008,2 )	
       	


insert into PAYROLL.DAILY_HANDS (CURR_DATE,
		DEPT_ID, 
	    ENTRY_TYPE,
		PERMANENTA,
		PERMANENTB,
		PERMANENTC,
		SPECIALBADLYA,
		SPECIALBADLYB,
		SPECIALBADLYC,
		BADLYA,
		BADLYB,
		BADLYC,
		LEARNERA,
		LEARNERB,
		LEARNERC,
		SEMISKILLEDA,
		SEMISKILLEDB,
		SEMISKILLEDC,
		NEWENTRANCEA,
		NEWENTRANCEB,
		NEWENTRANCEC,
		OUTSIDERA,
		OUTSIDERB,
		OUTSIDERC,
		OTHERMILLA,
		OTHERMILLB,
		OTHERMILLC,
		VOUCHERRETA,
		VOUCHERRETB,
		VOUCHERRETC) 
		
		 
		
		select '2018-02-25', DEPT_ID, 
	    ENTRY_TYPE,
		PERMANENTA,
		PERMANENTB,
		PERMANENTC,
		SPECIALBADLYA,
		SPECIALBADLYB,
		SPECIALBADLYC,
		BADLYA,
		BADLYB,
		BADLYC,
		LEARNERA,
		LEARNERB,
		LEARNERC,
		SEMISKILLEDA,
		SEMISKILLEDB,
		SEMISKILLEDC,
		NEWENTRANCEA,
		NEWENTRANCEB,
		NEWENTRANCEC,
		OUTSIDERA,
		OUTSIDERB,
		OUTSIDERC,
		OTHERMILLA,
		OTHERMILLB,
		OTHERMILLC,
		VOUCHERRETA,
		VOUCHERRETB,
		VOUCHERRETC
from PAYROLL.DAILY_HANDS where CURR_DATE='2018-02-24'














select * from payroll.SINGLE_HANDS


insert into payroll.SINGLE_HANDS(CURR_DATE, DEPT_ID, HAND_VALUE) SELECT '2018-02-23', DEPT_ID, HAND_VALUE FROM payroll.SINGLE_HANDS where CURR_DATE='2018-02-24'









select * from PAYROLL.RATE where CURR_DATE = (
SELECT max(curr_date) FROM PAYROLL.RATE WHERE CURR_DATE <= CURRENT_date) 

select * from payroll.production
select * from payroll.rate

select * from PAYROLL.DAILY_HANDS




       		
       		
select 		
			dept.dept_code,
			sum(PERMANENTA+PERMANENTB+PERMANENTC) as TPERMANENT,
			sum(SPECIALBADLYA+SPECIALBADLYB+SPECIALBADLYC) as TSPECIALBADLY,
			sum(BADLYA+BADLYB+BADLYC) as TBADLY,
			sum(LEARNERA+LEARNERB+LEARNERC) as TLEARNER,
			sum(SEMISKILLEDA+SEMISKILLEDB+SEMISKILLEDC) as TSEMISKILLED,
			sum(NEWENTRANCEA+NEWENTRANCEB+NEWENTRANCEC) as TNEWENTRANCE,
			sum(OUTSIDERA+OUTSIDERB+OUTSIDERC) as TOUTSIDER,
			sum(OTHERMILLA+OTHERMILLB+OTHERMILLC) as TOTHERMILL,
			sum(VOUCHERRETA+VOUCHERRETB+VOUCHERRETC) as TVOUCHERRET,
			sum(TOTAL) AS TOTAL
		from payroll.daily_hands DHANDS
			join payroll.dept dept
				on dept.dept_id = DHANDS.dept_id
		where 
			DHANDS.CURR_DATE between '2018-02-23' and '2018-02-25' group by dept.dept_code order by dept.dept_code 
			
SELECT 
		dept.dept_code,
		SUM(HANDS_VALUE) AS TOTAL
	FROM 
		PAYROLL.SINGLE_HANDS SHANDS
	where 
		SHANDS.CURR_DATE between '2018-02-23' and '2018-02-25' group by dept.dept_code order by dept.dept_code 
		

       		
       
			


 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 